/* token.h */

typedef enum {
        ID = 256, 
	NUM, 
        KEY,
        BOOLEAN,
        KCHAR,
        ELSE,
        FALSE,
        FOR,
        FUNCTION,
        IF,
        INTEGER,
        PRINT,
        RETURN,
        KSTRING,
        TRUE,
        VOID,
        WHILE,
        LEQ,
        GEQ,
        EQ,
        NEQ,
        AND,
        OR,
        SYM,  
        SYMC,
        CHAR,
	STR,
        ARRAY,        
        PLUS = 43,
        MINUS = 45,
        MULT = 42,
        DIV = 47,
        MOD = 37,
        NOT = 33,
        LT = 60,
        GT = 62,
        ASSIGN = 61,
        COLON = 58,
        SEMICOLON = 59,
        COMMA = 44,
        LPAREN = 40,
        RPAREN = 41,
        RBRACKET = 93,
        LBRACKET = 91,
        LBRACE = 123,
        RBRACE = 125,
        BACKSLASH = 92,


        
	ERROR
} token_t; 

